### ISSUE TITLE
Uvicorn import paths different than main.py’s, difficulties debugging

### ISSUE THREAD

**Issue by jdittrich** [rednafi/fastapi-nano#68]
(I hope I describe this correctly, it is _possible_ that I have a misunderstanding of how imports are resolved)

**Problem:** The [FastAPI documentation on debugging](https://fastapi.tiangolo.com/tutorial/debugging/) suggests to call uvicorn directly from main via the IDE/Debugger. However, in this case, fastapi-nano’s imports do not seem to work, as the folder of main.py is the root folder for the module imports with this method of executing the code. So `from app.core import auth` fails, , `from core import auth` would work. The imports work when calling uvicorn directly since `uvicorn app.main:app` (as documented in the readme) seems to make the module resolution uses the folder _uvicorn_ was called from as its root (that is, the project’s main folder with the folder app in it)

**Possible solutions:**
* Assume calling from the /app folder and change paths accordingly
* Document another way to debug
* Dont fix/not a significant problem

**Comment by rednafi** [comment]
`from core import auth` comes with its fair share of issues. Can you try `python -m main` instead of running the main module as a script? Running `python main.py` puts the path of the nested package to the top of the `sys.path` which can have other unintended consequences. You can learn more about it here:

https://rednafi.github.io/reflections/how-not-to-run-a-script-in-python.html

**Comment by rednafi** [comment]
Not an issue.
